{'application':{'type':'Application',
          'name':'Template',
    'backgrounds': [
    {'type':'Background',
          'name':'sc-viewer',
          'title':u'Smart Card Viewer',
          'size':(419, 460),
          'statusBar':1,
          'backgroundColor':(68, 68, 68),

        'menubar': {'type':'MenuBar',
         'menus': [
             {'type':'Menu',
             'name':'menuFile',
             'label':'&File',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuFileNew',
                   'label':'&New\tCtrl+N',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileOpen',
                   'label':'&Open\tCtrl+O',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileSave',
                   'label':'&Save\tCtrl+S',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileSaveAs',
                   'label':'Save &As...',
                  },
                  {'type':'MenuItem',
                   'name':'fileSep1',
                   'label':'-',
                  },
                  {'type':'MenuItem',
                   'name':'menuFilePageSetup',
                   'label':'Page Set&up...',
                  },
                  {'type':'MenuItem',
                   'name':'menuFilePrint',
                   'label':'&Print...\tCtrl+P',
                  },
                  {'type':'MenuItem',
                   'name':'menuFilePrintPreview',
                   'label':'Print Pre&view',
                  },
                  {'type':'MenuItem',
                   'name':'fileSep2',
                   'label':'-',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileExit',
                   'label':'E&xit\tAlt+X',
                   'command':'exit',
                  },
              ]
             },
             {'type':'Menu',
             'name':'Edit',
             'label':'&Edit',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuEditUndo',
                   'label':'&Undo\tCtrl+Z',
                  },
                  {'type':'MenuItem',
                   'name':'menuEditRedo',
                   'label':'&Redo\tCtrl+Y',
                  },
                  {'type':'MenuItem',
                   'name':'editSep1',
                   'label':'-',
                  },
                  {'type':'MenuItem',
                   'name':'menuEditCut',
                   'label':'Cu&t\tCtrl+X',
                  },
                  {'type':'MenuItem',
                   'name':'menuEditCopy',
                   'label':'&Copy\tCtrl+C',
                  },
                  {'type':'MenuItem',
                   'name':'menuEditPaste',
                   'label':'&Paste\tCtrl+V',
                  },
                  {'type':'MenuItem',
                   'name':'editSep2',
                   'label':'-',
                  },
                  {'type':'MenuItem',
                   'name':'menuEditClear',
                   'label':'Cle&ar\tDel',
                  },
                  {'type':'MenuItem',
                   'name':'menuEditSelectAll',
                   'label':'Select A&ll\tCtrl+A',
                  },
              ]
             },
             {'type':'Menu',
             'name':'menuHelp',
             'label':'&Help',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuHelpAbout',
                   'label':'&About ...',
                   'command':'doHelpAbout',
                  },
              ]
             },
         ]
     },
         'components': [

{'type':'StaticText', 
    'name':'lblAppTitle', 
    'position':(10, 10), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'style': 'bold', 'faceName': u'Arial', 'size': 14}, 
    'foregroundColor':(58, 255, 57, 255), 
    'text':u'Smart Card Viewer', 
    },

{'type':'TextArea', 
    'name':'txtMain', 
    'position':(10, 42), 
    'size':(399, 175), 
    'backgroundColor':(0, 105, 7, 255), 
    'font':{'faceName': u'Arial', 'size': 11}, 
    'foregroundColor':(92, 255, 85, 255), 
    'text':u'Smart Card Viewer', 
    },

{'type':'Button', 
    'name':'cmdDisconnect', 
    'position':(320, 270), 
    'backgroundColor':(85, 85, 85, 255), 
    'foregroundColor':(74, 255, 68, 255), 
    'label':u'Disconnect', 
    },

{'type':'Button', 
    'name':'cmdConnect', 
    'position':(320, 230), 
    'backgroundColor':(85, 85, 85, 255), 
    'foregroundColor':(77, 255, 78, 255), 
    'label':u'Connect', 
    },

] # end components
} # end background
] # end backgrounds
} }
